name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: pipeline_task
    type: string
    displayName: "Task"
    default: 'Plan only'
    values:
      - 'Plan only'
      - 'Plan and Apply'
      - 'Plan and Destroy'

  - name: targets
    type: object
    default:
    - resourcegroupName: YourResourcegroup

trigger:
  - none

stages:
- ${{ each target in parameters.targets }}:
  - stage: root_module_for_${{ replace(target.resourcegroupName, '-', '_')  }}
    condition: always()
    pool:
      vmImage: 'ubuntu-latest'

    jobs:
    - job: 
      steps:

      - checkout: self
        displayName: 'Checkout repository'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'sc-image-definition-devops-sc'
          scriptType: 'bash'
          inlineScript: |
            # Show Azure account details
            az account show

            # Set the working directory for Terraform commands
            WORKING_DIR="$(System.DefaultWorkingDirectory)/subscriptions/${{ target.resourcegroupName }}"

            # Initialize Terraform
            terraform -chdir=$WORKING_DIR init

            # Plan only
            if [ '${{parameters.pipeline_task}}' == 'Plan only' ]; then
              terraform -chdir=$WORKING_DIR plan
            fi

            # Plan and Apply
            if [ '${{parameters.pipeline_task}}' == 'Plan and Apply' ]; then
              terraform -chdir=$WORKING_DIR plan
              terraform -chdir=$WORKING_DIR apply -auto-approve
            fi

            # Plan and Destroy
            if [ '${{parameters.pipeline_task}}' == 'Plan and Destroy' ]; then
              terraform -chdir=$WORKING_DIR plan
              terraform -chdir=$WORKING_DIR destroy -auto-approve
            fi
        displayName: 'Run Terraform commands via Azure CLI'
